# version: '3.8'

# services:
#   app:
#     image: mcr.microsoft.com/devcontainers/javascript-node:20
#     volumes:
#       - ..:/workspaces/${localWorkspaceFolderBasename}
#     command: sleep infinity
#     depends_on:
#       - db

#   db:
#     image: postgres:15
#     restart: unless-stopped
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: coffee_app
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres-data:/var/lib/postgresql/data

# volumes:
#   postgres-data:
